---
# ansible-playbook site.yml -e "aws_access_key=xxxxxxxxxxxxxxxxxxxx aws_secret_key=xxxxxxxxxxxxxxxxxxx"
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning

    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      security_group: webserver
      tag_name: webserver
      count: 1

    # Task that will be used to Launch/Create an EC2 Instance
    tasks:

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for webserver Servers
          region: "{{ aws_region }}"
          vpc_id: "{{ aws_vpc_id }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8090
              to_port: 8090
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: web_sg

      - name: Launch the new EC2 Instance
        local_action:
          module: ec2
          group: "{{ security_group }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          instance_type: "{{ aws_instance_type }}"
          image: "{{ aws_ec2_ami }}"
          vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
          wait: yes
          region: "{{ aws_region }}"
          keypair: "{{ aws_key_name }}"
          count: "{{count}}"
          assign_public_ip: yes
          instance_tags:
            Name: "{{tag_name}}"
            Monitoring: "On"
            Environment: "{{aws_env}}"
        register: ec2

      - name: Add the newly created EC2 instance(s) to ansible inventory
        add_host:
          hostname: "{{ item.public_ip }}"
          ansible_user: "ubuntu"
          groups: "webserver"
        with_items: "{{ ec2.instances }}"

      - name: Add tag to Instance(s)
        local_action: 
          module: ec2_tag
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          resource: "{{web_sg.group_id}}"
          region: "{{ aws_region }}"
          state: present
          tags:
            Name: "{{ security_group }}"
            Environment: "{{aws_env}}"

      - name: Wait for SSH to come up
        wait_for:
          host: "{{ item.public_ip }}"
          port: 22 
          delay: 20
          timeout: 320
          state: started
        with_items: "{{ ec2.instances }}"

  - name: Setup wordpress and monitoring on EC2 Instance
    hosts: webserver              # define 'docker' as our action target
    become: yes
    become_method: sudo
    serial: 1          #define the action will be done one by one
    roles:
    - role: common     #define 'common' role should be apply to hosts
    - role: docker     #define 'docker' role should be apply to hosts
    - role: monitoring       #define 'monitoring' role should be apply to hosts
    - role: wordpress       #define 'monitoring' role should be apply to hosts
