---
# ansible-playbook terminate.yml -e "instance_ids=i-xxxxxx my_aws_access_key=xxxxxxxxxx my_aws_secret_key=xxxxxxxxxxxxxxxxxxx"
- name: Terminate instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: us-west-2
  tasks:
    - name: Delete instances
      ec2:
        state: absent
        aws_access_key: "{{ my_aws_access_key }}"
        aws_secret_key: "{{ my_aws_secret_key }}"
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'

    - name: "Delete group by its id"
      ec2_group:
        state: absent
        aws_access_key: "{{ my_aws_access_key }}"
        aws_secret_key: "{{ my_aws_secret_key }}"
        name: "webserver"
        description: ""
        region: '{{ region }}'
