---
# To run this playbook, change directory to `install` and run `bash ensure-infra-with-ansible.sh`
- name: Terminate instances
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    security_group: webserver

  tasks:
    - name: Delete instances
      ec2:
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: '{{ item }}'
        region: '{{ aws_region }}'
        wait: yes
      with_items:
        - "{{ wp_instance_ids }}"
        - "{{ mon_instance_ids }}"

    - name: "Delete group by its id"
      ec2_group:
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ security_group }}"
        description: ""
        region: '{{ aws_region }}'
