---
# ansible-playbook terminate.yml -e "instance_ids=i-xxxxxx aws_access_key=xxxxxxxxxx aws_secret_key=xxxxxxxxxxxxxxxxxxx"
- name: Terminate instances
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    security_group: webserver

  tasks:
    - name: Delete instances
      ec2:
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: '{{ instance_ids }}'
        region: '{{ aws_region }}'
        wait: yes

    - name: "Delete group by its id"
      ec2_group:
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ security_group }}"
        description: ""
        region: '{{ aws_region }}'
