---
- name: Create wordpress folder.
  file:
    path: /tmp/wordpress
    mode: 0755
    state: directory

- name: Copy wordpress config
  action: copy src=docker-compose-wordpress.yml dest=/tmp/wordpress/docker-compose.yml mode=0644

- name: start wordpress container
  shell: "docker-compose up -d"
  args:
    chdir: /tmp/wordpress

- name: Nginx setup
  apt: pkg=nginx state=installed

- name: Create includes folder.
  file:
    path: /etc/nginx/includes
    mode: 0755
    state: directory
  register: incl_dir

- name: Copy proxy config
  action: copy src=proxy.conf dest=/etc/nginx/includes/proxy.conf mode=0644
  when: incl_dir.changed

- name: Copy default config
  action: copy src=nginx.conf dest=/etc/nginx/sites-available/default mode=0644
  register: nginx_conf

- name: Start nginx
  service:
    name: nginx
    state: restarted
  when: nginx_conf.changed
