---
# Example checkout a github repo and use refspec to fetch all pull requests
- name: get monitoring solution
  git:
    repo: https://github.com/ravibhure/dockprom.git
    dest: /tmp/monitoring
    force: yes

- name: start monitoring
  shell: "docker-compose -f docker-compose.exporters.yml up -d"
  args:
    chdir: /tmp/monitoring
