---
# Example checkout a github repo and use refspec to fetch all pull requests
- name: get monitoring solution
  git:
    repo: https://github.com/ravibhure/dockprom.git
    dest: /tmp/monitoring

- name: copy ec2 discovery
  template: src=prometheus.yml.j2 dest=/tmp/monitoring/prometheus/prometheus.yml mode=0644

- name: copy docker compose for monitoring
  copy: src=docker-compose-monitoring.yml dest=/tmp/monitoring/docker-compose.yml mode=0644

- name: start monitoring
  shell: "docker-compose up -d"
  args:
    chdir: /tmp/monitoring

- name: "Wait for services to start"
  pause: seconds=30
