wordpress_db:
  image: mariadb
  ports:
    - 127.0.0.1:3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: ChangeMe
wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 80:80
