---
- name: apt update
  apt: update_cache=yes

- name: Install linux images
  shell: "apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual"

- name: Install base dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - libssl-dev
    - python-dev
    - python-setuptools
    - vim
    - sudo
    - curl
    - git
    - apt-transport-https
    - ca-certificates
    - python-pip
    - python-boto
    - jq
  tags: base
